#!/usr/bin/env python3
"""Generate reaper_lua_shim.h from the symbol list probed out of LuaSocket."""
import sys

with open(sys.argv[1]) as f:
    syms = [s.strip() for s in f if s.strip()]
# lua_settable is dead-stripped from REAPER; it is emulated, not resolved.
syms = [s for s in syms if s != "lua_settable"]
# Needed by the shim itself for the ABI guard, not by LuaSocket.
if "luaL_checkversion_" not in syms:
    syms.append("luaL_checkversion_")
syms.sort()

HEAD = '''/*
 * reaper_lua_shim.h -- route LuaSocket's Lua C API calls through REAPER's own
 * Lua runtime.
 *
 * REAPER embeds Lua 5.4 but keeps its C API symbols local (nm shows `t`, not
 * `T`), so dlopen/dlsym cannot bind them and a stock LuaSocket build fails to
 * load.  Statically linking liblua does load, but puts a second Lua runtime in
 * the process, which misreads REAPER-allocated long strings and silently drops
 * every response over 40 bytes.
 *
 * This header is force-included (clang -include) when compiling LuaSocket, so
 * every `lua_*` / `luaL_*` call becomes a call through a function pointer
 * resolved from REAPER's Mach-O symbol table at module load.  One runtime, no
 * embedded copy.
 *
 * The lua headers are included here, before the shadowing macros, so that the
 * declarations in lua.h are seen unshadowed.  LuaSocket's own `#include
 * "lua.h"` later is a no-op thanks to the include guards.
 *
 * GENERATED by gen_header.py from the symbols LuaSocket actually references.
 */

#ifndef REAPER_LUA_SHIM_H
#define REAPER_LUA_SHIM_H

#include <lua.h>
#include <lauxlib.h>
#include <lualib.h>

/* Every Lua C API symbol LuaSocket references, plus luaL_checkversion_ for the
 * ABI guard.  lua_settable is absent -- see reaper_shim_lua_settable below. */
#define REAPER_LUA_SHIM_SYMBOLS(X) \\
'''

TAIL_DECL = '''
/* One pointer per symbol, typed from the real prototype in lua.h. */
#define REAPER_LUA_SHIM_DECLARE(name) extern __typeof__(name) *reaper_p_##name;
REAPER_LUA_SHIM_SYMBOLS(REAPER_LUA_SHIM_DECLARE)
#undef REAPER_LUA_SHIM_DECLARE

/*
 * Resolve every symbol and verify the ABI.  Returns 1 on success, 0 if the
 * host binary is stripped or a symbol is missing -- callers must then refuse
 * to run rather than call through a NULL pointer.
 */
int reaper_lua_shim_init(lua_State *L);

/*
 * lua_settable has no entry in REAPER's symbol table: REAPER's own code never
 * calls it, so the linker dead-stripped it.  Every LuaSocket call site targets
 * a plain table it created itself with lua_newtable and never gave a metatable
 * -- upstream already uses lua_rawset on the same module table in base_open()
 * and select_open() -- so a raw set is exactly equivalent there.
 */
void reaper_shim_lua_settable(lua_State *L, int idx);

#ifndef REAPER_LUA_SHIM_IMPL

/* Shadow the API names for LuaSocket's translation units. */
'''

TAIL_END = '''
/* The real entry points wrap these, resolving symbols before LuaSocket runs. */
#define luaopen_socket_core reaper_ls_luaopen_socket_core
#define luaopen_mime_core   reaper_ls_luaopen_mime_core

#endif /* !REAPER_LUA_SHIM_IMPL */

#endif /* REAPER_LUA_SHIM_H */
'''

out = [HEAD]
for i, s in enumerate(syms):
    cont = " \\" if i < len(syms) - 1 else ""
    out.append("    X(%s)%s\n" % (s, cont))
out.append(TAIL_DECL)

width = max(len(s) for s in syms)
for s in syms:
    out.append("#define %-*s reaper_p_%s\n" % (width, s, s))
out.append("#define %-*s reaper_shim_lua_settable\n" % (width, "lua_settable"))
out.append(TAIL_END)

with open(sys.argv[2], "w") as f:
    f.write("".join(out))
print("wrote %s with %d resolved symbols + lua_settable emulation" % (sys.argv[2], len(syms)))
