/*
 * reaper_lua_shim.h -- route LuaSocket's Lua C API calls through REAPER's own
 * Lua runtime.
 *
 * REAPER embeds Lua 5.4 but keeps its C API symbols local (nm shows `t`, not
 * `T`), so dlopen/dlsym cannot bind them and a stock LuaSocket build fails to
 * load.  Statically linking liblua does load, but puts a second Lua runtime in
 * the process, which misreads REAPER-allocated long strings and silently drops
 * every response over 40 bytes.
 *
 * This header is force-included (clang -include) when compiling LuaSocket, so
 * every `lua_*` / `luaL_*` call becomes a call through a function pointer
 * resolved from REAPER's Mach-O symbol table at module load.  One runtime, no
 * embedded copy.
 *
 * The lua headers are included here, before the shadowing macros, so that the
 * declarations in lua.h are seen unshadowed.  LuaSocket's own `#include
 * "lua.h"` later is a no-op thanks to the include guards.
 *
 * GENERATED by gen_header.py from the symbols LuaSocket actually references.
 */

#ifndef REAPER_LUA_SHIM_H
#define REAPER_LUA_SHIM_H

#include <lua.h>
#include <lauxlib.h>
#include <lualib.h>

/* Every Lua C API symbol LuaSocket references, plus luaL_checkversion_ for the
 * ABI guard.  lua_settable is absent -- see reaper_shim_lua_settable below. */
#define REAPER_LUA_SHIM_SYMBOLS(X) \
    X(luaL_addlstring) \
    X(luaL_addstring) \
    X(luaL_argerror) \
    X(luaL_buffinit) \
    X(luaL_checkinteger) \
    X(luaL_checklstring) \
    X(luaL_checknumber) \
    X(luaL_checkoption) \
    X(luaL_checktype) \
    X(luaL_checkversion_) \
    X(luaL_error) \
    X(luaL_newmetatable) \
    X(luaL_optlstring) \
    X(luaL_optnumber) \
    X(luaL_prepbuffsize) \
    X(luaL_pushresult) \
    X(luaL_setfuncs) \
    X(luaL_testudata) \
    X(lua_callk) \
    X(lua_copy) \
    X(lua_createtable) \
    X(lua_error) \
    X(lua_getfield) \
    X(lua_getmetatable) \
    X(lua_gettable) \
    X(lua_gettop) \
    X(lua_isnumber) \
    X(lua_isstring) \
    X(lua_newuserdatauv) \
    X(lua_pcallk) \
    X(lua_pushboolean) \
    X(lua_pushcclosure) \
    X(lua_pushfstring) \
    X(lua_pushinteger) \
    X(lua_pushlstring) \
    X(lua_pushnil) \
    X(lua_pushnumber) \
    X(lua_pushstring) \
    X(lua_pushvalue) \
    X(lua_rawequal) \
    X(lua_rawget) \
    X(lua_rawgeti) \
    X(lua_rawset) \
    X(lua_rawseti) \
    X(lua_rotate) \
    X(lua_setfield) \
    X(lua_setmetatable) \
    X(lua_settop) \
    X(lua_toboolean) \
    X(lua_tolstring) \
    X(lua_tonumberx) \
    X(lua_touserdata) \
    X(lua_type) \
    X(lua_typename)

/* One pointer per symbol, typed from the real prototype in lua.h. */
#define REAPER_LUA_SHIM_DECLARE(name) extern __typeof__(name) *reaper_p_##name;
REAPER_LUA_SHIM_SYMBOLS(REAPER_LUA_SHIM_DECLARE)
#undef REAPER_LUA_SHIM_DECLARE

/*
 * Resolve every symbol and verify the ABI.  Returns 1 on success, 0 if the
 * host binary is stripped or a symbol is missing -- callers must then refuse
 * to run rather than call through a NULL pointer.
 */
int reaper_lua_shim_init(lua_State *L);

/*
 * lua_settable has no entry in REAPER's symbol table: REAPER's own code never
 * calls it, so the linker dead-stripped it.  Every LuaSocket call site targets
 * a plain table it created itself with lua_newtable and never gave a metatable
 * -- upstream already uses lua_rawset on the same module table in base_open()
 * and select_open() -- so a raw set is exactly equivalent there.
 */
void reaper_shim_lua_settable(lua_State *L, int idx);

#ifndef REAPER_LUA_SHIM_IMPL

/* Shadow the API names for LuaSocket's translation units. */
#define luaL_addlstring    reaper_p_luaL_addlstring
#define luaL_addstring     reaper_p_luaL_addstring
#define luaL_argerror      reaper_p_luaL_argerror
#define luaL_buffinit      reaper_p_luaL_buffinit
#define luaL_checkinteger  reaper_p_luaL_checkinteger
#define luaL_checklstring  reaper_p_luaL_checklstring
#define luaL_checknumber   reaper_p_luaL_checknumber
#define luaL_checkoption   reaper_p_luaL_checkoption
#define luaL_checktype     reaper_p_luaL_checktype
#define luaL_checkversion_ reaper_p_luaL_checkversion_
#define luaL_error         reaper_p_luaL_error
#define luaL_newmetatable  reaper_p_luaL_newmetatable
#define luaL_optlstring    reaper_p_luaL_optlstring
#define luaL_optnumber     reaper_p_luaL_optnumber
#define luaL_prepbuffsize  reaper_p_luaL_prepbuffsize
#define luaL_pushresult    reaper_p_luaL_pushresult
#define luaL_setfuncs      reaper_p_luaL_setfuncs
#define luaL_testudata     reaper_p_luaL_testudata
#define lua_callk          reaper_p_lua_callk
#define lua_copy           reaper_p_lua_copy
#define lua_createtable    reaper_p_lua_createtable
#define lua_error          reaper_p_lua_error
#define lua_getfield       reaper_p_lua_getfield
#define lua_getmetatable   reaper_p_lua_getmetatable
#define lua_gettable       reaper_p_lua_gettable
#define lua_gettop         reaper_p_lua_gettop
#define lua_isnumber       reaper_p_lua_isnumber
#define lua_isstring       reaper_p_lua_isstring
#define lua_newuserdatauv  reaper_p_lua_newuserdatauv
#define lua_pcallk         reaper_p_lua_pcallk
#define lua_pushboolean    reaper_p_lua_pushboolean
#define lua_pushcclosure   reaper_p_lua_pushcclosure
#define lua_pushfstring    reaper_p_lua_pushfstring
#define lua_pushinteger    reaper_p_lua_pushinteger
#define lua_pushlstring    reaper_p_lua_pushlstring
#define lua_pushnil        reaper_p_lua_pushnil
#define lua_pushnumber     reaper_p_lua_pushnumber
#define lua_pushstring     reaper_p_lua_pushstring
#define lua_pushvalue      reaper_p_lua_pushvalue
#define lua_rawequal       reaper_p_lua_rawequal
#define lua_rawget         reaper_p_lua_rawget
#define lua_rawgeti        reaper_p_lua_rawgeti
#define lua_rawset         reaper_p_lua_rawset
#define lua_rawseti        reaper_p_lua_rawseti
#define lua_rotate         reaper_p_lua_rotate
#define lua_setfield       reaper_p_lua_setfield
#define lua_setmetatable   reaper_p_lua_setmetatable
#define lua_settop         reaper_p_lua_settop
#define lua_toboolean      reaper_p_lua_toboolean
#define lua_tolstring      reaper_p_lua_tolstring
#define lua_tonumberx      reaper_p_lua_tonumberx
#define lua_touserdata     reaper_p_lua_touserdata
#define lua_type           reaper_p_lua_type
#define lua_typename       reaper_p_lua_typename
#define lua_settable       reaper_shim_lua_settable

/* The real entry points wrap these, resolving symbols before LuaSocket runs. */
#define luaopen_socket_core reaper_ls_luaopen_socket_core
#define luaopen_mime_core   reaper_ls_luaopen_mime_core

#endif /* !REAPER_LUA_SHIM_IMPL */

#endif /* REAPER_LUA_SHIM_H */
